import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

/**
 * Application router instance.
 * routeTree.gen.ts is auto-generated by @tanstack/router-vite-plugin on build.
 */
export const router = createRouter({ routeTree });

// Type-safe router augmentation
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
